---
- hosts: "{{target}}"
  become: yes
  gather_facts: no
  
  vars_files:
    - "secure_vars.yml"

  tasks:
    - name: Copy notify script
      template:
        src: notify.sh
        dest: /usr/local/bin/notify
        mode: "111"

    - name: Send test notification
      shell: notify "Updated notification script on {{target}}"