---
- hosts: "{{target}}"
  become: yes
  gather_facts: no
  
  vars:
    required_sys_packages:
      - software-properties-common
      - fail2ban
      - ufw
      - rsync
      - docker-ce
      - docker-ce-cli
      - python3
      - python3-pip
  
  tasks:
    - name: Add an Apt signing key for docker repository
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update index
      apt:
        state: latest
        update-cache: yes

    - name: Install/Update required apt packages
      apt:
        state: latest
        update-cache: yes
        cache_valid_time: 3600
        package: "{{required_sys_packages }}"
    
    - name: Install/Update global user packages
      apt:
        state: latest
        update-cache: yes
        cache_valid_time: 3600
        package: "{{additional_sys_packages | default([])}}"

    - name: Install/Update host user packages
      apt:
        state: latest
        update-cache: yes
        cache_valid_time: 3600
        package: "{{host_sys_packages | default([])}}"

    - name: Cleanup unused packages
      apt:
        autoremove: yes

    - name: Install docker lib for python
      pip:
        name: docker
        state: latest





